# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='user_id',
        ),
    ]
